# Generated by Django 4.1.7 on 2023-03-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing_id", models.CharField(blank=True, max_length=150, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("buy_price", models.CharField(blank=True, max_length=10, null=True)),
                ("category_path", models.TextField(blank=True, null=True)),
                ("photo_id", models.CharField(blank=True, max_length=15, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("sku_id", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "available_to_buy",
                    models.CharField(blank=True, default=0, max_length=10, null=True),
                ),
                (
                    "quantity_remaining",
                    models.CharField(blank=True, default=0, max_length=10, null=True),
                ),
                ("store_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sold_quantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("date", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoldProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing_id", models.CharField(blank=True, max_length=10, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("buy_price", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "sold_quantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("date", models.CharField(blank=True, max_length=10, null=True)),
                ("store_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="store",
            name="action",
            field=models.CharField(
                blank=True, default="inactive", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="date",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="store_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="store_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
