# Generated by Django 4.1.7 on 2023-03-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_products_soldproduct_store_action_store_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="action",
            field=models.CharField(
                blank=True, default="active", max_length=10, null=True
            ),
        ),
    ]
