# Generated by Django 4.1.7 on 2023-03-21 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_store_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="products",
            name="updated_at",
        ),
    ]
