# Generated by Django 4.1.7 on 2023-03-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_products_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="data_created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="data_updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
