# Generated by Django 4.1.7 on 2023-03-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_products_data_created_at_products_data_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="current_month",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="last_month",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="second_last_month",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
