# Generated by Django 4.1.7 on 2023-03-28 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_products_current_month_products_last_month_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="products",
            name="start_date",
        ),
    ]
